spring:
  application:
    name: studentinfoservice
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: password

#server:
#  servlet:
#    context-path: /studentinfo

server:   
  port: 8081